export const orderItemsMock: OrderItem[] = [
  {
    productId: "P-1001",
    productName: "Basmati Rice",
    quantity: 2,
    unit: "kg",
    pricePerUnit: 120,
    totalPrice: 240,
  },
  {
    productId: "P-1002",
    productName: "Whole Wheat Flour",
    quantity: 1,
    unit: "kg",
    pricePerUnit: 45,
    totalPrice: 45,
  },
  {
    productId: "P-1003",
    productName: "Fresh Milk",
    quantity: 3,
    unit: "litre",
    pricePerUnit: 50,
    totalPrice: 150,
  },
  {
    productId: "P-1004",
    productName: "Brown Bread",
    quantity: 2,
    unit: "loaf",
    pricePerUnit: 35,
    totalPrice: 70,
  },
  {
    productId: "P-1005",
    productName: "Organic Eggs",
    quantity: 12,
    unit: "pcs",
    pricePerUnit: 7,
    totalPrice: 84,
  },
  {
    productId: "P-1006",
    productName: "Cooking Oil",
    quantity: 1,
    unit: "litre",
    pricePerUnit: 160,
    totalPrice: 160,
  },
];
