export const mockProducts: ProductTableItem[] = [
  {
    id: "p1",
    productName: "Organic Apples",
    stock: "available",
    price: 120,
    qty: 50,
    unit: "kg",
  },
  {
    id: "p2",
    productName: "Whole Wheat Bread",
    stock: "available",
    price: 45,
    qty: 30,
    unit: "loaf",
  },
  {
    id: "p3",
    productName: "Fresh Milk",
    stock: "unavailable",
    price: 60,
    qty: 0,
    unit: "litre",
  },
  {
    id: "p4",
    productName: "Free-Range Eggs",
    stock: "available",
    price: 80,
    qty: 200,
    unit: "dozen",
  },
  {
    id: "p5",
    productName: "Basmati Rice",
    stock: "available",
    price: 95,
    qty: 100,
    unit: "kg",
  },
  {
    id: "p6",
    productName: "Cheddar Cheese",
    stock: "unavailable",
    price: 250,
    qty: 0,
    unit: "kg",
  },
  {
    id: "p7",
    productName: "Almond Butter",
    stock: "available",
    price: 350,
    qty: 25,
    unit: "jar",
  },
  {
    id: "p8",
    productName: "Greek Yogurt",
    stock: "available",
    price: 150,
    qty: 40,
    unit: "cup",
  },
  {
    id: "p9",
    productName: "Orange Juice",
    stock: "unavailable",
    price: 90,
    qty: 0,
    unit: "litre",
  },
  {
    id: "p10",
    productName: "Brown Rice",
    stock: "available",
    price: 80,
    qty: 60,
    unit: "kg",
  },
  {
    id: "p11",
    productName: "Coconut Oil",
    stock: "available",
    price: 300,
    qty: 15,
    unit: "litre",
  },
  {
    id: "p12",
    productName: "Honey",
    stock: "unavailable",
    price: 400,
    qty: 0,
    unit: "jar",
  },
  {
    id: "p13",
    productName: "Peanut Butter",
    stock: "available",
    price: 200,
    qty: 30,
    unit: "jar",
  },
  {
    id: "p14",
    productName: "Green Tea",
    stock: "available",
    price: 120,
    qty: 50,
    unit: "box",
  },
  {
    id: "p15",
    productName: "Pasta",
    stock: "available",
    price: 60,
    qty: 80,
    unit: "packet",
  },
  {
    id: "p16",
    productName: "Tomato Sauce",
    stock: "unavailable",
    price: 90,
    qty: 0,
    unit: "bottle",
  },
  {
    id: "p17",
    productName: "Mozzarella Cheese",
    stock: "available",
    price: 220,
    qty: 25,
    unit: "kg",
  },
  {
    id: "p18",
    productName: "Spinach",
    stock: "available",
    price: 40,
    qty: 35,
    unit: "bundle",
  },
  {
    id: "p19",
    productName: "Carrots",
    stock: "available",
    price: 35,
    qty: 45,
    unit: "kg",
  },
  {
    id: "p20",
    productName: "Potatoes",
    stock: "available",
    price: 25,
    qty: 90,
    unit: "kg",
  },
  {
    id: "p21",
    productName: "Onions",
    stock: "available",
    price: 20,
    qty: 80,
    unit: "kg",
  },
  {
    id: "p22",
    productName: "Garlic",
    stock: "unavailable",
    price: 60,
    qty: 0,
    unit: "kg",
  },
  {
    id: "p23",
    productName: "Ginger",
    stock: "available",
    price: 70,
    qty: 25,
    unit: "kg",
  },
  {
    id: "p24",
    productName: "Chicken Breast",
    stock: "available",
    price: 250,
    qty: 40,
    unit: "kg",
  },
  {
    id: "p25",
    productName: "Salmon Fillet",
    stock: "unavailable",
    price: 800,
    qty: 0,
    unit: "kg",
  },
  {
    id: "p26",
    productName: "Shrimp",
    stock: "available",
    price: 600,
    qty: 15,
    unit: "kg",
  },
  {
    id: "p27",
    productName: "Beef Steak",
    stock: "available",
    price: 700,
    qty: 20,
    unit: "kg",
  },
  {
    id: "p28",
    productName: "Lamb Chops",
    stock: "unavailable",
    price: 750,
    qty: 0,
    unit: "kg",
  },
  {
    id: "p29",
    productName: "Cucumber",
    stock: "available",
    price: 30,
    qty: 50,
    unit: "kg",
  },
  {
    id: "p30",
    productName: "Lettuce",
    stock: "available",
    price: 40,
    qty: 35,
    unit: "bundle",
  },
  {
    id: "p31",
    productName: "Broccoli",
    stock: "unavailable",
    price: 60,
    qty: 0,
    unit: "kg",
  },
  {
    id: "p32",
    productName: "Cauliflower",
    stock: "available",
    price: 55,
    qty: 40,
    unit: "kg",
  },
  {
    id: "p33",
    productName: "Zucchini",
    stock: "available",
    price: 45,
    qty: 25,
    unit: "kg",
  },
  {
    id: "p34",
    productName: "Bell Peppers",
    stock: "available",
    price: 60,
    qty: 30,
    unit: "kg",
  },
  {
    id: "p35",
    productName: "Mangoes",
    stock: "unavailable",
    price: 100,
    qty: 0,
    unit: "kg",
  },
  {
    id: "p36",
    productName: "Bananas",
    stock: "available",
    price: 50,
    qty: 60,
    unit: "dozen",
  },
  {
    id: "p37",
    productName: "Pineapples",
    stock: "available",
    price: 90,
    qty: 20,
    unit: "kg",
  },
  {
    id: "p38",
    productName: "Strawberries",
    stock: "available",
    price: 150,
    qty: 15,
    unit: "kg",
  },
  {
    id: "p39",
    productName: "Blueberries",
    stock: "unavailable",
    price: 200,
    qty: 0,
    unit: "kg",
  },
  {
    id: "p40",
    productName: "Raspberries",
    stock: "available",
    price: 180,
    qty: 10,
    unit: "kg",
  },
  {
    id: "p41",
    productName: "Watermelon",
    stock: "available",
    price: 30,
    qty: 50,
    unit: "kg",
  },
  {
    id: "p42",
    productName: "Papaya",
    stock: "available",
    price: 45,
    qty: 40,
    unit: "kg",
  },
  {
    id: "p43",
    productName: "Kiwi",
    stock: "available",
    price: 120,
    qty: 25,
    unit: "kg",
  },
  {
    id: "p44",
    productName: "Avocado",
    stock: "unavailable",
    price: 200,
    qty: 0,
    unit: "kg",
  },
  {
    id: "p45",
    productName: "Cherries",
    stock: "available",
    price: 250,
    qty: 15,
    unit: "kg",
  },
  {
    id: "p46",
    productName: "Plums",
    stock: "available",
    price: 100,
    qty: 20,
    unit: "kg",
  },
  {
    id: "p47",
    productName: "Pears",
    stock: "unavailable",
    price: 90,
    qty: 0,
    unit: "kg",
  },
  {
    id: "p48",
    productName: "Grapes",
    stock: "available",
    price: 80,
    qty: 35,
    unit: "kg",
  },
  {
    id: "p49",
    productName: "Dates",
    stock: "available",
    price: 300,
    qty: 20,
    unit: "kg",
  },
  {
    id: "p50",
    productName: "Figs",
    stock: "unavailable",
    price: 350,
    qty: 0,
    unit: "kg",
  },
];
