export const selfPickUpsMockData: SelfPickUpsTableItem[] = [
  {
    id: "SPU-1001",
    shopName: "FreshMart Grocery",
    amount: 450,
    noProducts: 5,
    status: "pending",
  },
  {
    id: "SPU-1002",
    shopName: "Daily Bakes",
    amount: 320,
    noProducts: 3,
    status: "accepted",
  },
  {
    id: "SPU-1003",
    shopName: "Techie Gadgets",
    amount: 1500,
    noProducts: 2,
    status: "rejected",
  },
  {
    id: "SPU-1004",
    shopName: "Spice & Rice",
    amount: 890,
    noProducts: 7,
    status: "confirm",
  },
  {
    id: "SPU-1005",
    shopName: "GreenLeaf Organics",
    amount: 600,
    noProducts: 4,
    status: "pending",
  },
  {
    id: "SPU-1006",
    shopName: "City Electronics",
    amount: 2999,
    noProducts: 1,
    status: "accepted",
  },
  {
    id: "SPU-1007",
    shopName: "Bake My Day",
    amount: 250,
    noProducts: 2,
    status: "confirm",
  },
];
